### ISSUE TITLE
Cannot Authenticate

### ISSUE THREAD

**Issue by davewehr** [joeyhage/homebridge-alexa-smarthome#106]
**Describe Your Problem:**

I am having trouble authenticating the plugin. Using my iPad, I accessed the local host URL from my home bridge log and the website appears as expected, but then I am immediately redirected to the App Store listing for the Amazon Alexa app—note that I already have the app installed. If I try from my MacBook, I get a QR code to scan; if I scan it with my phone, the same things happens, it bounces me over to the App Store listing.

Note that I did already set up Amazon with the Google Authenticator app. I also tied two different proxy ports (9000 and 7000) but that change had no effect.

My Alexa app has two hostnames listed:

na-api-Alexa.amazon.com
Alexa.amazon.com

None of those are options in the drop-down, so I selected amazon.com. Since that did not work, I went into the JSON config and tried both of the above options, one at a time—this had no effect.

**Logs:**

```

[homebridge-alexa-smarthome] Failed to initialize connection to Alexa. - Please open http://Homebridge.local:7000/ with your browser and login to Amazon. The cookie will be output here after successfull login.
[29/01/2024, 18:03:27] 
[homebridge-alexa-smarthome] After initialization - HttpError(Error getting smart home devices. Reason: Cookie invalid, Renew unsuccessful)

```

**Plugin Config:**

```json

{
    "devices": [],
    "auth": {
        "refreshInterval": 4,
        "proxy": {
            "clientHost": "Homebridge.local",
            "port": 7000
        }
    },
    "amazonDomain": "alexa.amazon.com",
    "language": "en-US",
    "performance": {
        "cacheTTL": 30,
        "backgroundRefresh": true
    },
    "debug": false,
    "_bridge": {
        "username": "0E:FD:92:73:0D:C5",
        "port": 39578
    },
    "platform": "HomebridgeAlexaSmartHome"
}

```

**Screenshots:**

N/a

**Environment:**

- **Plugin Version**: 2.1.2
- **Homebridge Version**: homebridge -V1.7.0 UI 4.55.1
- **Node.js Version**: node -v20.10.0
- **NPM Version**: npm -v???
- **Operating System**: Raspbian GNU/Linux Bullseye (11)

**Comment by joeyhage** [comment]
Closing due to duplicate
