### ISSUE TITLE
Sengled RGB bulb shown as white bulb

### ISSUE THREAD

**Issue by gonzlog** [joeyhage/homebridge-alexa-smarthome#107]
I have 2 RGB Sengled Smart Bluetooth Light bulbs (with no hub required) working in Alexa, but in HomeKit those are shown as white bulbs and can only turn on and off, but no color control.

![IMG_0918](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/28687049/a46b15bb-b54a-4d79-9cf3-e9eca9cd624b)
![IMG_0919](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/28687049/489c30d7-3f89-48e2-a1af-f1df7fe212a0)

**Environment:**

- **Plugin Version**: v2.1.2
- **Homebridge Version**: v1.7.0
- **Node.js Version**: v20.9.0
- **Operating System**:  Docker on Synology DSM 7.2.1

**Comment by joeyhage** [comment]
Support for color was added in v2.2.0
