### ISSUE TITLE
Similarly named devices won't add to HK

### ISSUE THREAD

**Issue by rhy5davie5** [joeyhage/homebridge-alexa-smarthome#111]
**Describe The Bug:**
I have 2 devices in Alexa, one is named Laptop Charger, one is called Rocket Charger, both are TP Link Kasa HS100 smart plugs.
If I add 'Laptop Charger', it won't add 'Rocket Charger'. If I rename 'Rocket Charger' to 'Rocket Charge' in Alexa, it recognises and adds OK.

**To Reproduce:**
Add 2 devices with the same last name??

**Expected behavior:**

**Logs:**
No log to show

**Plugin Config:**
{
    "devices": [
        "Hallway Lamp",
        "Rocket Charge",
        "Laptop Charger",

**Screenshots:**

**Environment:**

- **Plugin Version**: v2.1.0
- **Homebridge Version**: 4.55.1
- **Node.js Version**: v18.19.0
- **NPM Version**: Unknown
- **Operating System**:  Raspbian

**Comment by rhy5davie5** [comment]
Sorry, TP Link Kasa HS100 Plugs

**Comment by rhy5davie5** [comment]
Also, I have 2 devices in Alexa called 'Garage Heat 1' and 'Garage Heat 2', which are also TP Link Kasa HS100 Plugs.
The plugin recognised and added them into HK successfully but one is programmed as a power socket, the other one as a 'switch'

**Comment by joeyhage** [comment]
Some people have reported that old device names, if you have renamed devices, can cause problems. If you are still seeing this issue, you should try re-linking those devices.

The plugin adds devices to Homekit with the same device type as Alexa.
