### ISSUE TITLE
HttpError(Error getting smart home device state. Reason: Timeout)

### ISSUE THREAD

**Issue by mewanas1209** [joeyhage/homebridge-alexa-smarthome#115]
}
} END capabilities for all devices
[2/17/2024, 8:53:25 PM] [HomebridgeAlexaSmartHome] After initialization - HttpError(Error getting smart home device state. Reason: Timeout)

{
    "devices": [],
    "excludeDevices": [],
    "auth": {
        "refreshInterval": 4,
        "proxy": {
            "clientHost": "192.168.x.xx",
            "port": 8921
        }
    },
    "amazonDomain": "amazon.com",
    "language": "en-US",
    "performance": {
        "cacheTTL": 307,
        "backgroundRefresh": true
    },
    "debug": true,
    "platform": "HomebridgeAlexaSmartHome"

**Comment by joeyhage** [comment]
Please try using only a few devices by listing the names in the plugin settings. See if that helps. This issue usually occurs when there are too many devices

**Comment by mewanas1209** [comment]
Hey Joey,

Thanks for the Reply. I did remove several devices and still timing out.

[image0.jpeg]
Thank you,

Meena Wanas, Pharm D. MSCR

"But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint." Isaiah 40:31

On Feb 18, 2024, at 11:55 AM, Joey Hage ***@***.***> wrote:

﻿

Please try using only a few devices by listing the names in the plugin settings. See if that helps. This issue usually occurs when there are too many devices

**Comment by mewanas1209** [comment]
Hey Joey,

I tried to add specific devices again and it worked. I had to completely delete the plugin and reinstall. However, It still doesn’t pull the full list like it used to.

Thank you,

Meena Wanas, Pharm D. MSCR

"But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint." Isaiah 40:31

On Feb 18, 2024, at 3:39 PM, Meena Wanas ***@***.***> wrote:

﻿
Hey Joey,

Thanks for the Reply. I did remove several devices and still timing out.

<image0.jpeg>

Thank you,

Meena Wanas, Pharm D. MSCR

"But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint." Isaiah 40:31

On Feb 18, 2024, at 11:55 AM, Joey Hage ***@***.***> wrote:

﻿

Please try using only a few devices by listing the names in the plugin settings. See if that helps. This issue usually occurs when there are too many devices

**Comment by JustinRudebaugh** [comment]
I'm having the same issue on a brand new install of the plug in.  I've gone through and put in individual devices as well.

**Comment by joeyhage** [comment]
This is likely related to the rate limiting that Amazon is doing. Please see #137 for context.

**Comment by joeyhage** [comment]
This was fixed in v2.2.0

**Comment by mewanas1209** [comment]
When I go home tonight I will take a screenshot, but after the last homebridge upgrade/node it quit working again.

Thank you,

Meena Wanas, Pharm D. MSCR

"But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint." Isaiah 40:31

On Aug 13, 2024, at 11:17 PM, Joey Hage ***@***.***> wrote:

﻿

This was fixed in v2.2.0
