### ISSUE TITLE
Issue : After initialization - HttpError(Error getting smart home device state. Reason: no body)

### ISSUE THREAD

**Issue by planemaker1974** [joeyhage/homebridge-alexa-smarthome#125]
Hi, 
I am a newbie on homebridge so sorry if this question is a basic one
The description to install this. plugin was very clear and even steps like the cookie and the access was done quite easily
Now I see this message of error and of course, I dont get devices from Alexa to homekit. 

I tried to restrict to one single device and named it accurately but still not difference

Thanks!

 Done

**Describe Your Problem:**

Message of error shown above

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**
Réglages: Homebridge Alexa Smart Home
×
Include device names
List of smart home device names to add as HomeKit accessories. If no devices are specified, the plugin will attempt to add all supported accessories.

Bedside lamp daddy
Exclude devices
List of smart home device names to exclude from being added as HomeKit accessories. Exclude devices will only be excluded if 'Include device names' is empty.

Amazon domain

amazon.com
The Amazon domain that your devices are registered to.

Two character language code hyphen two character country code
en-US
Language for Alexa authentication.

Authorization and authentication settings
Refresh interval
4
How often this plugin should automatically refresh the session with Amazon. Defaults to every 4 days.

Proxy Client Host
Proxy Client Host *
192.168.1.91
A current IP address or hostname of the Homebridge host that is accessible from the web browser where you will authenticate from.

Proxy port *

7214
The port to run the authentication proxy on.

Performance
Device state cache lifetime

30
Refresh Alexa device states every __ seconds. Higher values will allow this plugin to work faster if you are noticing 'This plugin slows down Homebridge' messages in the Homebridge logs. However, higher values also means device states may be less accurate.

By default, device states are only updated when requested. For example, when the Home app is opened. If you notice 'This plugin slows down Homebridge' messages in the Homebridge logs, it is recommended to enable background refresh and set the 'Device state cache lifetime' to a value of 300 or more.

Whether to enable debug logging for troubleshooting issues and support.

```json
Show your Homebridge config.json here, remove any sensitive information.
{
    "devices": [
        "Bedside lamp daddy"
    ],
    "excludeDevices": [],
    "auth": {
        "refreshInterval": 4,
        "proxy": {
            "clientHost": "192.168.1.91",
            "port": 7214
        }
    },
    "amazonDomain": "amazon.com",
    "language": "en-US",
    "performance": {
        "cacheTTL": 30,
        "backgroundRefresh": true
    },
    "debug": true,
    "_bridge": {
        "username": "0E:16:CD:55:3C:5D",
        "port": 54947
    },
    "platform": "HomebridgeAlexaSmartHome"
}

**Screenshots:**

<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**

- **Plugin Version**:
- **Homebridge Version**: <!-- homebridge -V -->
- **Node.js Version**: <!-- node -v -->
- **NPM Version**: <!-- npm -v -->
- **Operating System**: <!-- Raspbian / Ubuntu / Debian / Windows / macOS / Docker / hb-service -->

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by joeyhage** [comment]
This should be fixed as of v2.2.0
