### ISSUE TITLE
Color changing lights siri/Home kit support

### ISSUE THREAD

**Issue by CarryptoKnight** [joeyhage/homebridge-alexa-smarthome#126]
**Is your feature request related to a problem? Please describe:**
When asking siri to change the colors of the lights siri responds "none of the lights in "specific location" (i.e. living room, bedroom, etc.) have color control

**Describe the solution you'd like:**
Can you please add color changing support? The specific lights not working are Lumary smart LED can lights. The lights can be turned on and off and adjusted to specific brightness levels via siri and homekit, however, the color changing feature is not working via Siri and/or homekit

**Describe alternatives you've considered:**
I have tried uninstalling and reinstalling the bridge

**Additional context:**

**Comment by joeyhage** [comment]
Color support was added in v2.2.0
