### ISSUE TITLE
Was working now not

### ISSUE THREAD

**Issue by bkballer917** [joeyhage/homebridge-alexa-smarthome#130]
Initialize Devices - UnsupportedDeviceError(Unsupported device: AC with type: THERMOSTAT. Currently supported device types are: LIGHT,SWITCH,SMARTLOCK,SMARTPLUG,THERMOSTAT,ALEXA_VOICE_ENABLED,AIR_QUALITY_MONITOR,VACUUM_CLEANER,GAME_CONSOLE,AIR_FRESHENER.)

**Comment by joeyhage** [comment]
Interesting that this was fixed with 2.1.5. It must be related to the rate limiting that Amazon is doing. Please see #137 for context.

**Comment by joeyhage** [comment]
ACs are not officially supported by this plugin. I do not have access to a smart AC so I am unable to support it. If you would like to contribute to the project, I am happy to review any code.
