### ISSUE TITLE
Smart Home Error

### ISSUE THREAD

**Issue by GreatBazunka-eng** [joeyhage/homebridge-alexa-smarthome#132]
After a new installation of the plugin I am getting the error 

[6/12/2024, 5:47:44 PM] [HomebridgeAlexaSmartHome] After initialization - RequestUnsuccessful(Error getting smart home device state(s). Response: {
  "message": "Too many requests. Try again in some time."

I have tried reinstalling the plugin, clearing all config, and installing an older version. This error started suddenly last night.

**Logs:**

There are no logs currently

**Plugin Config:**

{
    "devices": [],
    "excludeDevices": [],
    "auth": {
        "refreshInterval": 4,
        "proxy": {
            "clientHost": "192.168.1.185",
            "port": 9000
        }
    },
    "amazonDomain": "amazon.com",
    "language": "en-US",
    "performance": {
        "cacheTTL": 30,
        "backgroundRefresh": false
    },
    "debug": false,
    "platform": "HomebridgeAlexaSmartHome"
}

**Comment by cesans** [comment]
I am having the same issue for a new instalation.

**Comment by fmottaz** [comment]
Same for me, seems to have started between yesterday and today

**Comment by CrisNevares** [comment]
Fixed with 2.1.5!

**Comment by joeyhage** [comment]
Fixed in 2.2.0
