### ISSUE TITLE
Additional details on deploying a local checkout of the plugin

### ISSUE THREAD

**Issue by claycoleman** [joeyhage/homebridge-alexa-smarthome#135]
**Describe Your Problem:**

Hi @joeyhage , amazing plugin! I'm interested in trying to build out additional functionality for smart air conditioners. I can get the app cloned and running, but I'm interested in how I can get homebridge to use my local checkout of the plugin instead of the version installed in homebridge. The CONTRIBUTING.md has a lot of details about getting set up and putting up changes for review, but not much about how to get it running with your local homebridge while you're developing.

Appreciate the help here and look forward to putting up some code!

**Comment by joeyhage** [comment]
Glad to hear you want to contribute and great question! My local development process involves using `npm run watch` which starts a homebridge server on the development machine. By default, it doesn't include the homebridge ui but that can be added to the homebridge config. 

Is that what you are trying to do or are you trying to test the changes on the Homebridge server you use for your devices?

**Comment by joeyhage** [comment]
Closing due to no response.
