### ISSUE TITLE
lack of air conditioning control

### ISSUE THREAD

**Issue by grzech1991** [joeyhage/homebridge-alexa-smarthome#136]
I can't use air conditionier, in the log i have problem

[6/19/2024, 6:05:27 PM] [homebridge-alexa-smarthome] Klimatyzator - Set power - RequestUnsuccessful(Error setting smart home device state. Response: {
  "controlResponses": [],
  "errors": [
    {
      "entity": {
        "entityId": "8ce63d2e-321a-48b6-b069-d77aa816f0f6",
        "entityType": "APPLIANCE"
      },
      "code": "TargetApplianceUnreachableException",
      "message": "ENDPOINT_UNREACHABLE",
      "data": null
    }
  ]
}. Error code: TargetApplianceUnreachableException)

situation occurs when the air conditioner turned off from the remote control and I try to turn it on from the app

- **Plugin Version**: newest
- **Homebridge Version**: newest
- **Operating System**:  synology

**Comment by joeyhage** [comment]
Based on this message, Alexa is not able to communicate with the device when it is powered off. Likely, the device's Wifi connection is severed when it is turned off. Either the device needs to be kept on and put into a sleep/inactive mode or you need to turn it on with the remote before attempting to control it.
