### ISSUE TITLE
Unsupported Device

### ISSUE THREAD

**Issue by najeetpie** [joeyhage/homebridge-alexa-smarthome#141]
Initialize Devices - UnsupportedDeviceError(Unsupported device: Front Door with type: SMARTLOCK. Currently supported device types are: LIGHT,SWITCH,SMARTLOCK,SMARTPLUG,THERMOSTAT,ALEXA_VOICE_ENABLED,AIR_QUALITY_MONITOR,VACUUM_CLEANER,GAME_CONSOLE,AIR_FRESHENER.)

Says this type of device is unsupported but it is also listed under the supported devices

**Comment by mynameisbrendan** [comment]
I have the same issue after upgrading to v2.2.0.  I downgraded back to v.2.1.5 to restore my smartlock device

**Comment by najeetpie** [comment]
> I have the same issue after upgrading to v2.2.0. I downgraded back to v.2.1.5 to restore my smartlock device

When I try that, I get the too many requests error

**Comment by jeanofthedead** [comment]
> > I have the same issue after upgrading to v2.2.0. I downgraded back to v.2.1.5 to restore my smartlock device
> 
> When I try that, I get the too many requests error

I get that on every single version... you don't?

**Comment by najeetpie** [comment]
> > > I have the same issue after upgrading to v2.2.0. I downgraded back to v.2.1.5 to restore my smartlock device
> > 
> > 
> > When I try that, I get the too many requests error
> 
> I get that on every single version... you don't?

I do get it on every version

**Comment by mynameisbrendan** [comment]
My smartlock works on 2.1.5.  Its a Gainsborough Freestyle.

**Comment by joeyhage** [comment]
I plan to have a new alpha version for 2.2.0 published in a few hours. Please comment on #138 if you see this issue after I release the new alpha.
