### ISSUE TITLE
Devices states are not updated 

### ISSUE THREAD

**Issue by vicky1631** [joeyhage/homebridge-alexa-smarthome#144]
**Is your feature request related to a problem? Please describe:**
When I control the devices that are linked to HomeKit via this plugin from their native apps for example from Dyson app for the air purifier. The device status is not updated in the home app even after 60 seconds which is the default interval set. 

it’s annoying as I have to switch between multiple apps to know their actual status and can’t really trust the devices status that are linked using this plugin. 

**Describe the solution you'd like:**
if you look at Tuya plugin they update the status of the device almost instantly which makes it so reliable using only the home app. 

if I control the device from their native app the status such as turned ON or OFF must be instantly updated in the home app 

**Describe alternatives you've considered:**

**Additional context:**

**Comment by joeyhage** [comment]
Can you please share which version of this plugin you are using?

**Comment by vicky1631** [comment]
Hi Joey,

I am using the latest version V2.2.0-alpha.2

With Regards,
Vikram

**Comment by fmottaz** [comment]
If I may chime in, my Dyson Air purifier is directly linked to HomeKit from the Dyson App settings. Is it not the case with all models ?

**Comment by vicky1631** [comment]
Yup, mine is not HomeKit certified.

With Regards,
Vikram

**Comment by joeyhage** [comment]
Please upgrade to the latest alpha version 2.2.0-alpha.3 and let me know if it has improved at all.

**Comment by joeyhage** [comment]
Closing due to no response.

**Comment by vicky1631** [comment]
> Closing due to no response.

Sorry it completely slipped my mind to follow up on the issue. Today I have set up the plugin again with my home bridge and I noticed that the device status on the HomeKit app does not get updated at all even after the default 60second interval. The scenario I tried is with a Fan. I turned on the Fan using its native app and then checked immediately on Alexa app if the status was updated and yes in Alexa ios app it was promptly updated. Then I opened apple honkit app waited for a few minutes but no change at all. Only if I restart the plugin the status gets updated. I tried decreasing the status sync interval but any given value is below 30 then the plugin stops working entirely with an error in homebridge log. So I tried setting up with 30 seconds but even then no luck. Request you to please look into this issue since using the plugin to control devices on HomeKit app becomes void if it doesn't show the updated status of the device.
