### ISSUE TITLE
AC without Temperature Sensor doesn't work

### ISSUE THREAD

**Issue by ArkhanDev** [joeyhage/homebridge-alexa-smarthome#158]
**Describe The Bug:**

it is jot possible to control an AC which has no Temperature Sensor

**Expected behavior:**

Set the Temperature Value based on the current Cooling/Heating Temperature set

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

- **Plugin Version**:
- **Homebridge Version**: 
- **Node.js Version**: 
- **NPM Version**: 
- **Operating System**:

**Comment by joeyhage** [comment]
@ArkhanDev Hi Arkhan, ACs are not officially supported by this plugin. I do not have access to a smart AC so I am unable to support it. If you would like to contribute to the project, I am happy to review any code.
