### ISSUE TITLE
Problems accessing the Alexa app.

### ISSUE THREAD

**Issue by and43a** [joeyhage/homebridge-alexa-smarthome#30]
Hello and thank you for this wonderful plugin that we have been waiting for for years now.
I don't understand why I can't access the Alexa app.
1 install in plugin
2 set clientHost and port
3 I click on the generated link
4 a web page opens with a QR code that I scan with my phone, and instead of opening the Alexa app to continue, the search browser opens with my IP address etc.
how can I solve it? Thank you

**Comment by and43a** [comment]
solved thanks anyway

**Comment by joeyhage** [comment]
@and43a in case it helps others, could you please share how you solved it?

**Comment by and43a** [comment]
Yes… Of course, I was wrong to enter the IP address. you just need to put the address without http://   etcAndrea RussoIl giorno 9 set 2023, alle ore 19:54, Joey Hage ***@***.***> ha scritto:﻿
@and43a in case it helps others, could you please share how you solved it?

**Comment by and43a** [comment]
Of course, I was wrong to enter the IP address. you just need to put the address without http:// etc

**Comment by and43a** [comment]
Thank you for your amazing work

**Comment by joeyhage** [comment]
Thank you! Happy to hear the plug-in is helpful to you, @and43a
