### ISSUE TITLE
Request to support switch and Echo Glow. Smart plug help

### ISSUE THREAD

**Issue by joeyhage** [joeyhage/homebridge-alexa-smarthome#31]
From [Reddit](https://www.reddit.com/r/homebridge/comments/16ffq29/a_question_for_a_plugin_developer_but_anyone_can/):

First off, big kudos for your plug-in; it’s been working grate and does not seem to have slowed down home bridge, but I’ve got a couple of requests. Any chance we could see support added for switches, the Echo Glow, and the temperature sensors on Amazon Echo devices? Also, I noticed the update for Alexa media player support, but could you throw in the ability to airplay to Echo devices as well?

Adding switches and the Echo Glow should be pretty straightforward given your existing architecture for smart outlets and lightbulbs. But those Echo temperature sensors might be a tougher nut to crack, especially if you don’t have one to play with. I’d love to pitch in and help, but honestly, coding isn’t my strong suit, especially with the way your plug-in is structured.

Now, here’s the bigger issue that I think affects the whole Homebridge community. There’s a bug; the plug-in just doesn’t recognize one of my smart plugs. It’s all set up correctly in the Amazon Alexa app, but it’s MIA in HomeKit. I even removed three Echo devices from the list that tells the plug-in to add them, thinking there might be a device limit or something. But no luck. Any ideas on how to fix this?

Thanks a bunch for considering these requests and giving some insight.

Cheers, Andrew

**Comment by joeyhage** [comment]
1. Switch support should be very easy and I own one already I can test with.
2. I don’t have an Echo Glow but I should be able to add on/off and brightness easily. Color is a lot trickier and I haven’t solved that yet for lightbulbs because Alexa and Apple use very different data for color.
3. So you added this device name (case sensitive) to the plug-in settings, are there any error messages in the Homebridge logs for this plugin?

**Comment by YoaverageApplefanboy** [comment]
Hi. Sorry for my delayed response. Regarding airplay, what I was thinking you could do is possibly develop an Alexa skill that would simulate the Alexa media player. You could then use the homebridge server as the air playing location. I’m not sure if one device can advertise multiple airplay speakers, but if that is possible, then this probably would work.

as for the Amazon echo error messages, I’m actually getting two different ones. I connected all three of our echo devices with temperature sensors into the plug-in, and for two of them I’m getting the following error: [9/11/2023, 9:40:40 PM] [HomebridgeAlexaSmartHome dining Room echo - Get active - InvalidResponse(No media player information found) and [9/11/2023, 9:40:39 PM] [HomebridgeAlexaSmartHome] Master bedroom Echo - Get active - InvalidResponse(No media player information found) For the other one, I’m getting this error: [9/11/2023, 9:40:40 PM] [HomebridgeAlexaSmartHome] Andrew's Echo - Get active result: null I am getting the same error except replace active with volume. I’m also gettingp and logs that it’s registering the ability for the echo devices to trigger temperature and occupancy sensing. I didn’t see anything in there about the miss behaving smart plug. And finally, yes, please do add power and brightness control for the echo glow. They go on sale a lot of times on Amazon if you want a test unit. I saw one for around $16.

**Comment by joeyhage** [comment]
Thanks for the information! 

The skill idea is interesting but would require cloud infrastructure and all the maintenance and costs that go along with it. All said and done, it would be cheaper to buy a device that supports AirPlay like a HomePod or AppleTV.

For the Echo error messages, those errors are indicating that nothing is playing on the device so there is nothing to control. Since AirPlay is not supported and HomeKit doesn’t support any methods to choose media/music, something must already be playing.

If you happen to use Spotify and want a convenient way to start a playlist on a device, you can check out another plugin I support: https://github.com/joeyhage/homebridge-spotify-speaker

**Comment by joeyhage** [comment]
For the plug and echo glow, can you please turn on debug logging in the plugin settings? That will provide extra logging about the devices upon startup which would be very helpful for me to help troubleshoot. Thanks!

**Comment by YoaverageApplefanboy** [comment]
Hi. Sorry once again for the delayed response. It looks like the plug-in log debugging setting was already turned on. I didn’t see anything about the echo glow or smart plug in there. Before, one of my smart plugs was showing up. I change the name of it in the Alexa app and updated it in the plug-in settings, however it is not showing up anymore. this plug is one of the plugs on an Amazon basic power strip, and the other two plugs seem to be showing up fine and can both be controlled.

Also, again regarding airplay, instead of running cloud infrastructure, you could actually possibly use the home bridge instance as the server. However, there will just have to be a warning saying that it would slow down the computer a lot, as I am assuming that it would do so. If not, then you could implement it that way.

**Comment by YoaverageApplefanboy** [comment]
Also, regarding airplay, there is already a program that you can use as a baseline for airplay integration.

**Comment by joeyhage** [comment]
Creating an Alexa skill requires cloud infrastructure since that is where the skill executes, it does not execute on the Echo device (source: I've built Alexa skills before).

**Comment by YoaverageApplefanboy** [comment]
OK, I do understand that, but what I am now asking is why couldn’t you use the home bridge instance as the cloud infrastructure for the skill?

**Comment by joeyhage** [comment]
Ah I see what you are saying. Generally, skills are hosted in AWS. But the skill has to be hosted from one server - in other words, it’s not possible to have the skill run on my homebridge instance when I use it and your homebridge instance when you use it.

So hosting it on the homebridge instance would mean hosting it within my personal server for the use of everyone 😬

**Comment by joeyhage** [comment]
Can you send me a copy of the config JSON, specifically just the section for this plugin?

If your echo glow device is listed in the config, and the name matches what Alexa has exactly, you will see something like: 

```
[9/12/2023, 12:10:54 PM] [homebridge-alexa-smarthome] Attempting to add accessory: {
"id": "redacted",
"displayName": "your echo glow name",
```

again, these have to match exactly uppercase and lowercase and spaces

**Comment by YoaverageApplefanboy** [comment]
here is that section of the configuration file.

{
            "devices": [
                "andrew's window fan",
                "Andrews air purifier",
                "Andrew’s air conditioner",
                "bathroom fan",
                "Craft room Air Conditioner",
                "First  floor air purifier",
                "Kitchen light",
                "Master bedroom air conditioner",
                "Princess House",
                "Andrew’s home bridge server charger",
                "Kitchen Echo glow",
                "Andrew's Echo",
                "Dining room Echo",
                "Master bedroom Echo"
            ],
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": “xx.x.x.xx",
                    "port": xxxx
                }
            },
            "amazonDomain": "amazon.com",
            "language": "en-US",
            "performance": {
                "cacheTTL": 30,
                "backgroundRefresh": true
            },
            "debug": true,
            "platform": "HomebridgeAlexaSmartHome"
        },

**Comment by YoaverageApplefanboy** [comment]
Also, regarding airplay, here are two of my last suggestions on how to implement it. 1: Connect the echo devices to the HomeBridge server with Bluetooth. 2: add the homebridge instance to the Alexa app and allow it to be added to multiple music groups with the echo devices. These could be automatically created by the plug-in or manually by the user, and hopefully there would be an option to switch between the two modes.

**Comment by joeyhage** [comment]
Given the name of your device is `Kitchen Echo glow` and debug is enabled, you will see a message like

```
Attempting to add accessory: {
"id": "redacted",
"displayName": "Kitchen Echo glow",
...
}
```

I need to see that full log message so I know how to add Echo Glow support because I am in the dark without it. Thanks!
