### ISSUE TITLE
I can't get to the amazon log in page through my browser...  Keep getting a http...  I change this to HTTPS

### ISSUE THREAD

**Issue by njackson442** [joeyhage/homebridge-alexa-smarthome#34]
I can't authenticate login on browser.  It says to go to app but i click on the top to proceed to web address.  It then takes me to a http// address.  I switch this to http:// and then get the last screen shot of a 404

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

- **Plugin Version**: 2.2 Beta 3
(https://github.com/joeyhage/homebridge-alexa-smarthome/assets/144946144/ae20b6f6-b216-47c2-bac1-8b0aa3622b24)

- **Homebridge Version**:  1.6.1
- **Node.js Version**:  18.17.1
- **NPM Version**: 
- **Operating System**:  docker

![alexa2](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/144946144/d6cbdd98-285c-453f-90d2-bb6e13996836)
![alexa1](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/144946144/9f71ef40-0a2c-4e37-917c-70518da98ae8)
![alexa3](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/144946144/7973b976-cfda-427d-834e-b607993910fa)

**Comment by joeyhage** [comment]
What URL do you use to manage your homebridge plugins and can you please share the config you are using for this plugin?

**Comment by njackson442** [comment]
![image](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/144946144/48168b32-a780-4b7c-836f-4df1c1f2fa64)
 I use 192.168.1.44:4444 for homebridge

**Comment by joeyhage** [comment]
You need to remove the `http://` from `clientHost`

**Comment by njackson442** [comment]
That made progress...

Now i get this

![image](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/144946144/2ade9256-a211-4f44-aaf7-593689e6ed7c)

**Comment by joeyhage** [comment]
Just visiting 192.168.1.44:8827 and try again. If that still doesn’t work, please enable 2FA on your Amazon account

**Comment by njackson442** [comment]
That worked thank you!

**Comment by njackson442** [comment]
You ROck
