### ISSUE TITLE
choose devices

### ISSUE THREAD

**Issue by and43a** [joeyhage/homebridge-alexa-smarthome#37]
It would be nice to have an option in the settings that lets you choose which devices to appear in the home app.

>

**Comment by joeyhage** [comment]
If I’m understanding correctly, you’re asking for a setting that already exists.
![IMG_4980](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/3220319/cb42d846-f80b-48aa-904f-b21b74a52fb7)

**Comment by and43a** [comment]
Opsssss I’m sorry Inviato da Andrea RussoIl giorno 14 set 2023, alle ore 13:43, Joey Hage ***@***.***> ha scritto:﻿
If I’m understanding correctly, you’re asking for a setting that already exists.

**Comment by joeyhage** [comment]
No worries!
