### ISSUE TITLE
Initial Configuration Issue - Alexa Login URL 404 Error

### ISSUE THREAD

**Issue by blinkhappy** [joeyhage/homebridge-alexa-smarthome#40]
**Describe Your Problem:**

I have not been able to make it through the Initial configuration of this Homebridge Plugin. After successfully installing the Plugin in Homebridge, I entered my Proxy Client Host and selected a Proxy port as well as amazon domain. I then entered the URL found in my Homebridge log. This took me to an Amazon page with the text “404 Sorry, we couldn’t find that page. Don’t have the app installed? Download the Alexa App (link). Go to the Alexa App (link)” 

This is clearly not the Amazon login page that I was intended to land on. Is there anything you can think of that I’m doing wrong? 

In step 
 
I’m trying to configure this Alexa Homebridge Plugin.

**Logs:**

17/09/2023, 13:36:52] [HomebridgeAlexasmartHome] Failed to initialize connection to Alexa.
You can try to get the cookie manually by opening http://Homebridge. local: 8887/ with your brow ser.
[17/09/2023, 13:36:521 [HomebridgeAlexaSmartHomelAfter initialization - HttpError(Error getti ng smart home devices. Reason: Cookie invalid, Renew unsuccessful)
[17/09/2023, 13:36:52] Homebridge v1.6.1 (HAP v0. 11.1) (Homebridge 649C) is running on port 51
876.

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

{
            "devices": [],
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": "Homebridge.local",
                    "port": 8887
                }
            },
            "amazonDomain": "amazon.com",
            "language": "en-US",
            "performance": {
                "cacheTTL": 30,
                "backgroundRefresh": false
            },
            "debug": false,
            "platform": "HomebridgeAlexaSmartHome"
        }
    ]

**Screenshots:**
![image](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/24380583/2fb316d5-406d-46bb-b851-196bc30df3a7)

**Environment:**

- **Plugin Version**: v1.0.2
- **Homebridge Version**:  v1.6.1
- **Node.js Version**:  v18.7.1
- **NPM Version**:  
- **Operating System**: 
- Raspbian

**Comment by joeyhage** [comment]
Hi @blinkhappy, have you tried the instructions in the [common issues](https://github.com/joeyhage/homebridge-alexa-smarthome#common-issues) section yet?

**Comment by joeyhage** [comment]
To confirm, you installed the Alexa app and logged in to the same account on the app, you have MFA enabled on your account, and then you restarted homebridge?

**Comment by Stef1972** [comment]
Yes I did.

I logged in the home bridge.local:9000, I received the OTP, then I received a 'page not found' error. I did that on my mobile where the Alexa app is installed and logged with the same user I used for the plugin

**Comment by joeyhage** [comment]
Is it the same 404 as before or a new 404 page? Sometimes trying to load the page again (homebridge.local:9000 in your case) works

**Comment by joeyhage** [comment]
You might also have better luck using a desktop computer to access homebridge.local:9000. It’s just the login expects the Alexa app installed somewhere 😃

**Comment by Stef1972** [comment]
I tried form my mac and it did the same. 
![IMG_5018](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/79631344/be3cab80-6790-4fcf-ab41-67cef8b0a6cf)

**Comment by Stef1972** [comment]
http://homebridge.local:9000/www.amazon.com/404

**Comment by joeyhage** [comment]
What country are you located in? Have you tried a different Amazon domain than Amazon.com?

**Comment by Stef1972** [comment]
it seems I'm all able to access if I use amazon.com, but every time I restart home bridge I loose the configuration

**Comment by joeyhage** [comment]
As soon as it is successful, it saves the information to the persist file for the next time so make sure you don’t delete that file once it’s successful

**Comment by Stef1972** [comment]
yes, but sadly the file in the persist directory dosn't exist and it neve has been created

**Comment by joeyhage** [comment]
Since it starts with a period, it sometimes doesn’t show up unless you `ls -Al`

**Comment by Stef1972** [comment]
true. The file is there. So why I need to authenticate every time ?
I can also add this information. 
If I choose amazon.it it ask me for the OTP and then it says error 404
If I choose amazon.com just after the user and password it says Cookie successfully retrieved without asking me the otp

**Comment by joeyhage** [comment]
It depends on the Alexa marketplace your account is registered with. You can check in the app settings:

![IMG_4997](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/3220319/4727e830-7068-4845-9067-7234e1e218e0)

![IMG_4998](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/3220319/fc55a532-ea84-4cb9-a1f4-fd5ba6f59b56)

**Comment by Stef1972** [comment]
eu-api-alexa.amazon.it
alexa.amazon.it

**Comment by Stef1972** [comment]
other strange thing is: i have 3 echo dots. One of them is not on the list of the accessories in the account (i enabled the debug flag, and it shows the list of the accessories)

**Comment by joeyhage** [comment]
If it’s not showing, it maybe is associated with another account as primary, is disabled, might be in kids mode, a number of things can cause that. You could try removing it and adding it to your account again

**Comment by joeyhage** [comment]
@blinkhappy were you able to resolve the issue?

**Comment by blinkhappy** [comment]
Yes. Not sure what changed to make it work but thanks for getting back to
me.
