### ISSUE TITLE
After initialization - HttpError(Error getting smart home device state. Reason: no body)

### ISSUE THREAD

**Issue by Swissschoggi** [joeyhage/homebridge-alexa-smarthome#41]
Hello,

I have recently purchased some outdoor lights and integrated them into alexa as there is no homebridge plugin for these zigbee lights (+ i do not own an alexa lol) but they show up in the Alexa app.

Now if i try to set up the plugin in homebridge for Alexa i get multiple errors, every time i try it.

here are some of them all after setting it up and changing the config a couple of times to troubleshoot:

`After initialization - HttpError(Error getting smart home device state. Reason: no body)`
`Failed to initialize connection to Alexa. - Error while checking Authentication: Error: 401 Unauthorized`
`After initialization - HttpError(Error getting smart home devices. Reason: 401 Unauthorized)`

here also the plugin config
```json
{
            "devices": [
                "garden"
            ],
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": "172.168.1.205",
                    "port": 9000
                }
            },
            "amazonDomain": "amazon.com",
            "language": "de-CH",
            "performance": {
                "cacheTTL": 30,
                "backgroundRefresh": true
            },
            "debug": false,
            "_bridge": {
                "username": "0E:11:97:D9:B1:4A",
                "port": 49399
            },
            "platform": "HomebridgeAlexaSmartHome"
        }
```

- running the plugin version  v1.0.2
- homebridge version v1.6.1
- Node.js Version v18.16.0
- NPM Version 9.5.1
- OS Ubuntu Jammy Jellyfish (22.04.2 LTS)

**Comment by Swissschoggi** [comment]
literally just got a new log error:
`1 devices found in plugin settings but only 0 matched.`

**Comment by joeyhage** [comment]
Hi @Swissschoggi, can you please look at this similar issue to see if changing your Amazon domain helps? https://github.com/joeyhage/homebridge-alexa-smarthome/issues/40#issuecomment-1723775752

**Comment by Swissschoggi** [comment]
Thanks for the response.

So silly me, i changed the Amazon domain and realized i had to name the devices the same as in the Alexa app, it works now.
I feel pretty stupid but at least it's working.

Thanks

**Comment by joeyhage** [comment]
Excellent! 😄
