### ISSUE TITLE
Alexa Echo Dot not working

### ISSUE THREAD

**Issue by warshoot3r** [joeyhage/homebridge-alexa-smarthome#43]
**Describe The Bug:**
Getting an error. Alexa dot is not being set up. Not shown in homekit or homebridge

**To Reproduce:**

Set up amazon details on Amazon UK 
**Expected behavior:**

**Logs:**

```

[26/09/2023, 10:06:51] [HomebridgeAlexaSmartHome] Successfully authenticated Alexa account.
[26/09/2023, 10:06:51] [HomebridgeAlexaSmartHome] After initialization - InvalidResponse(Invalid list of Alexa devices found for the current Alexa account: {
  "success": true
})
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.

        {
            "devices": [],
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": "homebridge.local",
                    "port": 9000
                }
            },
            "amazonDomain": "amazon.co.uk",
            "language": "en-GB",
            "performance": {
                "cacheTTL": 31,
                "backgroundRefresh": false
            },
            "debug": true,
            "platform": "HomebridgeAlexaSmartHome"
        }

```

**Screenshots:**

**Environment:**

- **Plugin Version**:
- **Homebridge Version**: 
- **Node.js Version**: 
- **NPM Version**: 
- **Operating System**:

**Comment by joeyhage** [comment]
Can you please share the plugin version you are using and a screenshot of the Host Names in your Alexa app settings? See https://github.com/joeyhage/homebridge-alexa-smarthome#initial-configuration for an example

**Comment by warshoot3r** [comment]
I am using
` homebridge-alexa-smarthome v1.0.3`

Regarding the screenshots, see below: 
![image](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/28788772/acd0ef9d-2d18-4d8d-9697-e31aafa62a8f)
![image](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/28788772/339b62bd-603b-4e32-92d7-ea4268652ea4)
![image](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/28788772/1dc6f86c-78dc-4574-8132-d1eadf842f5f)
Thanks in advance !

**Comment by warshoot3r** [comment]
I checked , it's defintely the right account.

**Comment by alexelmi** [comment]
facing the same issue, were there any ideas?

**Comment by joeyhage** [comment]
My suggestion would be to explicitly list all the devices in the plugin settings. The Alexa API works a lot better that way. I added that recommendation to the README today as well.
