### ISSUE TITLE
Amazon.in domain

### ISSUE THREAD

**Issue by sumit-tokas** [joeyhage/homebridge-alexa-smarthome#64]
**Describe The Bug:**

Unable to see amazon.in as an amazon domain in the plugin setting.

**To Reproduce:**

During the installation of the plugin, the settings does not allow to use amazon.in domain as it does not appear in the list

**Expected behavior:**

amazon.in domain should be present in the domain list.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

{
    "bridge": {
        "name": "Homebridge 0966",
        "username": "--------",
        "port": ---------,
        "pin": "--------",
        "advertiser": "ciao",
        "bind": [
            "eth0"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "devices": [
                "Tube Light",
                "Ceiling Light"
            ],
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": "192.168.1.10",
                    "port": 9192
                }
            },
            "language": "en-IN",
            "performance": {
                "cacheTTL": 30,
                "backgroundRefresh": true
            },
            "debug": false,
            "_bridge": {
                "username": "---------",
                "port": ---------
            },
            "platform": "HomebridgeAlexaSmartHome"
        }
    ]
}

**Screenshots:**

<img width="800" alt="image" src="https://github.com/joeyhage/homebridge-alexa-smarthome/assets/41648104/b923be9a-2066-4448-980f-eb84f2ee5fe3">

**Environment:**

- **Plugin Version**: 2.0.1
- **Homebridge Version**: 1.6.1
- **Node.js Version**: 18.18.2
- **NPM Version**: 
- **Operating System**: macOS

**Comment by joeyhage** [comment]
This was fixed a couple months ago, this issue didn't auto close for some reason. Closing now.
