### ISSUE TITLE
Levoit Air Purifier not recognised as a device

### ISSUE THREAD

**Issue by Rich2k** [joeyhage/homebridge-alexa-smarthome#69]
**Describe The Bug:**

I have a Levoit Core 200S air purifier with Alexa support. Unfortunately I get the following error inside HomeBridge

`Initialize Devices - UnsupportedDeviceError(Unsupported device: Air Filter with type: AIR_PURIFIER. Currently supported device types are: LIGHT,SWITCH,SMARTLOCK,SMARTPLUG,THERMOSTAT,ALEXA_VOICE_ENABLED,AIR_QUALITY_MONITOR.)`

**To Reproduce:**

Simply have an Alexa supported device of type AIR_PURIFIER in your setup and the error will occur in the logs

**Expected behavior:**

**Logs:**

```
Initialize Devices - UnsupportedDeviceError(Unsupported device: Air Filter with type: AIR_PURIFIER. Currently supported device types are: LIGHT,SWITCH,SMARTLOCK,SMARTPLUG,THERMOSTAT,ALEXA_VOICE_ENABLED,AIR_QUALITY_MONITOR.)
```

**Plugin Config:**

**Screenshots:**

**Environment:**

- **Plugin Version**: 2.0.1
- **Homebridge Version**:  1.7.9
- **Node.js Version**:  20.9.0
- **NPM Version**:  10.1.0
- **Operating System**:  macOS

**Comment by joeyhage** [comment]
Hi @Rich2k, are you still interested in having air purifiers supported? I don't own one so I would need your help with testing and getting information about how the air purifier communicates with Alexa.

To start, I would need you to enable debug logging in the Homebridge alexa smarthome settings and share the output like another person did here: https://github.com/joeyhage/homebridge-alexa-smarthome/issues/95.

**Comment by joeyhage** [comment]
Closing due to no response.
