### ISSUE TITLE
Devices to add to accessories

### ISSUE THREAD

**Issue by junior120872** [joeyhage/homebridge-alexa-smarthome#71]
I have 93 devices discovered from Alexa but they don't get put into accessories.  I can manual add one from the list, but I thought it would auto populate them

[11/12/2023, 12:48:42 PM] [HomebridgeAlexaSmartHome] Initializing HomebridgeAlexaSmartHome platform...
[11/12/2023, 12:48:42 PM] [HomebridgeAlexaSmartHome] Initializing child bridge 0E:98:74:63:89:02
Setup Payload:
X-HM://00252KP08RVTH
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 968-17-560 │     
    └────────────┘     
                       
[11/12/2023, 12:48:42 PM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 026F) is running on port 51544.
[11/12/2023, 12:48:43 PM] [homebridge-alexa-smarthome] Launched child bridge with PID 13368
[11/12/2023, 12:48:44 PM] Registering platform 'homebridge-alexa-smarthome.HomebridgeAlexaSmartHome'
[11/12/2023, 12:48:44 PM] [homebridge-alexa-smarthome] Loaded homebridge-alexa-smarthome v2.0.1 child bridge successfully
[11/12/2023, 12:48:44 PM] Loaded 1 cached accessories from cachedAccessories.0E9874638902.
[11/12/2023, 12:48:44 PM] [homebridge-alexa-smarthome] Loading accessory from cache: Living Room Lamp
[11/12/2023, 12:48:44 PM] [homebridge-alexa-smarthome] Alexa-Remote: cookie was provided
[11/12/2023, 12:48:44 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-alexa-smarthome) is running on port 34514.
[11/12/2023, 12:48:44 PM] [homebridge-alexa-smarthome] Alexa-Remote: Authentication checked: true
[11/12/2023, 12:48:45 PM] [homebridge-alexa-smarthome] Alexa-Remote: Change Base URL for API calls to na-api-alexa.amazon.com
[11/12/2023, 12:48:47 PM] [homebridge-alexa-smarthome] Successfully authenticated Alexa account.
[11/12/2023, 12:48:48 PM] [homebridge-alexa-smarthome] Found 93 devices connected to the current Alexa account.
[11/12/2023, 12:48:48 PM] [homebridge-alexa-smarthome] BEGIN devices connected to Alexa account

 [
  {
    "displayName": "Dining Room lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Family Room Outlet",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Man Cave Lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "RV Parking ",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "Master Bedroom lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Jordan's Room Lights",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Patio",
    "deviceType": "CONTACT_SENSOR"
  },
  {
    "displayName": "Henry's Room Roku",
    "deviceType": "TV"
  },
  {
    "displayName": "Cat Lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Bonus Room Glow",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Coach Spot Door",
    "deviceType": "CONTACT_SENSOR"
  },
  {
    "displayName": "Stairs Lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Samsung Q60BA 60 TV",
    "deviceType": "TV"
  },
  {
    "displayName": "Garage Access",
    "deviceType": "CONTACT_SENSOR"
  },
  {
    "displayName": "Master Bedroom Echo Show",
    "deviceType": "ALEXA_VOICE_ENABLED"
  },
  {
    "displayName": "Man Cave Roku",
    "deviceType": "TV"
  },
  {
    "displayName": "Cabinet lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Henry's Echo Show",
    "deviceType": "ALEXA_VOICE_ENABLED"
  },
  {
    "displayName": "Front Door",
    "deviceType": "CONTACT_SENSOR"
  },
  {
    "displayName": "Henry’s LED",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Master Bath Shower",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Bathroom Flex light",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Porch lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Patio",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "Monkey Lamp",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Close GD nightly",
    "deviceType": "SCENE_TRIGGER"
  },
  {
    "displayName": "Fan",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Arcade plug",
    "deviceType": "SMARTPLUG"
  },
  {
    "displayName": "TV",
    "deviceType": "TV"
  },
  {
    "displayName": "Foyer motion",
    "deviceType": "MOTION_SENSOR"
  },
  {
    "displayName": "Blue Lamp",
    "deviceType": "SMARTPLUG"
  },
  {
    "displayName": "Vader",
    "deviceType": "SMARTPLUG"
  },
  {
    "displayName": "Downstairs Bath Motion",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Back Yard",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "Open Garage Door",
    "deviceType": "SCENE_TRIGGER"
  },
  {
    "displayName": "Man Cave",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "Lady Light",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Front Door",
    "deviceType": "SMARTLOCK"
  },
  {
    "displayName": "Hallway lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "iRoomba",
    "deviceType": "VACUUM_CLEANER"
  },
  {
    "displayName": "Lights",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Man Cave Left Front",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Q90",
    "deviceType": "TV"
  },
  {
    "displayName": "Man Cave Right Back",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Close Garage Door",
    "deviceType": "SCENE_TRIGGER"
  },
  {
    "displayName": "Sliding Door",
    "deviceType": "CONTACT_SENSOR"
  },
  {
    "displayName": "Jordan's Room Roku",
    "deviceType": "TV"
  },
  {
    "displayName": "White Lamp",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Driveway",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "Home",
    "deviceType": "THERMOSTAT"
  },
  {
    "displayName": "Close Garage",
    "deviceType": "SCENE_TRIGGER"
  },
  {
    "displayName": "Wireless Router",
    "deviceType": "NETWORK_HARDWARE"
  },
  {
    "displayName": "Henry’s Room Lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Home",
    "deviceType": "SECURITY_PANEL"
  },
  {
    "displayName": "Beaverton Ring",
    "deviceType": "SECURITY_PANEL"
  },
  {
    "displayName": "Foyer lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Man Cave Door",
    "deviceType": "SMARTLOCK"
  },
  {
    "displayName": "Living Room",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "TV light",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Kids Hall lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Master Bedroom Roku",
    "deviceType": "TV"
  },
  {
    "displayName": "Open Garage",
    "deviceType": "SCENE_TRIGGER"
  },
  {
    "displayName": "Family Room",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "Default white",
    "deviceType": "SCENE_TRIGGER"
  },
  {
    "displayName": "Man Door",
    "deviceType": "CONTACT_SENSOR"
  },
  {
    "displayName": "Kitchen motion",
    "deviceType": "MOTION_SENSOR"
  },
  {
    "displayName": "TV",
    "deviceType": "TV"
  },
  {
    "displayName": "Kitchen Echo Show",
    "deviceType": "OTHER"
  },
  {
    "displayName": "Hallway Echo",
    "deviceType": "ALEXA_VOICE_ENABLED"
  },
  {
    "displayName": "TBH",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "Patio Lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Master Bath tub",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Man Cave Door",
    "deviceType": "CONTACT_SENSOR"
  },
  {
    "displayName": "Man Cave Right Front",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Nook lights",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Living room Roku",
    "deviceType": "TV"
  },
  {
    "displayName": "Kitchen Lights",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Bonus Room",
    "deviceType": "CAMERA"
  },
  {
    "displayName": "Man Cave Left Back",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Bonus Room Lamp",
    "deviceType": "LIGHT"
  },
  {
    "displayName": "Laundry Room Motion",
    "deviceType": "SWITCH"
  },
  {
    "displayName": "Q90",
    "deviceType": "TV"
  },
  {
    "displayName": "Bonus Room Roku",
    "deviceType": "TV"
  },
  {
    "displayName": "Living Room Lamp",
    "deviceType": "LIGHT"
  }
]

END devices connected to Alexa account
[11/12/2023, 12:48:48 PM] [homebridge-alexa-smarthome] 0 devices provided in settings but 93 matching Alexa smart home devices were discovered.

```
Show the Homebridge logs here, remove any sensitive information.
```

 {
            "devices": [],
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": "localhost",
                    "port": 7951
                }
            },
            "amazonDomain": "amazon.com",
            "language": "en-US",
            "performance": {
                "cacheTTL": 30,
                "backgroundRefresh": false
            },
            "debug": true,
            "_bridge": {
                "username": "0E:98:74:63:89:02",
                "port": 34514
            },
            "platform": "HomebridgeAlexaSmartHome"
        }

```json
Show your Homebridge config.json here, remove any sensitive information.
```
{
    "bridge": {
        "name": "Homebridge 026F",
        "username": "0E:91:4E:49:CF:A0",
        "port": 51544,
        "pin": "968-17-560",
        "advertiser": "avahi",
        "bind": [
            "enp0s3"
        ]
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "navi-blue",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "devices": [],
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": "localhost",
                    "port": 7951
                }
            },
            "amazonDomain": "amazon.com",
            "language": "en-US",
            "performance": {
                "cacheTTL": 30,
                "backgroundRefresh": false
            },
            "debug": true,
            "_bridge": {
                "username": "0E:98:74:63:89:02",
                "port": 34514
            },
            "platform": "HomebridgeAlexaSmartHome"
        }
    ]
}
**Screenshots:**

**Environment:**

Node v20.9.0
 npm version 9.2.0

**Comment by joeyhage** [comment]
Sorry for the long delay here - several others have reported issues with the auto populate so my recommendation is to list all the devices. I have also added that recommendation to the plugin documentation. I will close this issue then since auto populate is no longer recommended. Thanks!
