### ISSUE TITLE
Unable to link

### ISSUE THREAD

**Issue by jayewyo** [joeyhage/homebridge-alexa-smarthome#78]
**Describe Your Problem:**
I have gone through all the setup and I receive the successfully retrieved cookie notification. However, when it tries to startup with that, I get this error: “ bridgeHomebridgeAlexaSmartHomeERRORAfter initialization - HttpError(Error getting smart home devices. Reason: Cookie invalid, Renew unsuccessful)”

Ive gone through it multiple times and got the same result. MFA is on. 
It almost looks like it’s not getting saved properly. 

**Logs:**

12/3/2023, 9:32:32 AMHoobs bridgeHomebridgeAlexaSmartHomeAlexa-Cookie: Result: csrf=4921321, Cookie=session-id=133-0927576-7526369; session-id-time=2332341152l; ubid-main=132-2371216-6320700; x-main=v2wTt?dxbl7Cj8e3dw5YvuqczrUBUhm1; at-main=Atza|IwEBIDCoxopzSEDJS2HmXXnHlsYOQ3XqvaUPiYVtA6Sso1q6bVjgTMQKodJzFSsPDrqLEUiCppPdISZaHwBCsynGLx3-_4lSMRPXR1EArmjaCTNpXE2p-9u5Mj5cQ_C1QOgOnnEJcK4ltxsjrgSEUmRFsveMgCqYfoHL7u0Z9x0VyuQTFPgnMqoE5sWhAUAjNsBaUXcnuyE3X9UZCn6Hbwm2yG7BErVZoLfpEJtUNgAmq7cpMF-wTEHDA0dZ89gSJt5XZbtP4eVYW0fLPThUnJ7gktwFkcAzGpppkzgcmcpTxENssXPqwD-MPBkVrIY5Ca8H_JW1_g3qyEFtlPanyLakTu_sczuSkZeDA09qRFT08S3VXsDx7-Mw3SVtwu1k1fdAkiLantkPwKPEldHEECcdj59C; sess-at-main=DisraQx6TEGZy1XDl9epxaGMgi/J0CU2Xt1r/9quydw=; csrf=4921321
12/3/2023, 9:32:32 AMHoobs bridgeHomebridgeAlexaSmartHomeAlexa login cookie updated. Storing cookie in file: /var/lib/hoobs/hoobsbridge/persist/.homebridge-alexa-smarthome
12/3/2023, 9:32:42 AMHoobs bridge starting
12/3/2023, 9:32:46 AMHoobs bridgeLoaded plugin 'homebridge-alexa-smarthome'
12/3/2023, 9:32:46 AMHoobs bridgeLoaded plugin 'homebridge-lennox-icomfort'
12/3/2023, 9:32:47 AMHoobs bridgeLoaded plugin 'homebridge-myq'
12/3/2023, 9:32:48 AMHoobs bridgeLoaded plugin 'homebridge-platform-insteonlocal'
12/3/2023, 9:32:48 AMHoobs bridgeLoaded plugin 'homebridge-smartthings-ik'
12/3/2023, 9:32:48 AMHoobs bridgeLoading 5 platforms...
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalStarted connection watcher...
12/3/2023, 9:32:48 AMHoobs bridgemyQERRORNo myQ login credentials configured.
12/3/2023, 9:32:48 AMHoobs bridgeLennoxIComfortFinished initializing platform: undefined
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalLoading accessory from cache: Entry Hall Lights
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalLoading accessory from cache: Family room lamps
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalLoading accessory from cache: Nightstand lamps
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalLoading accessory from cache: Living Room lamps
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalLoading accessory from cache: Porch lights
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalLoading accessory from cache: Basement leak sensor
12/3/2023, 9:32:48 AMHoobs bridgeSmartthings Plug (IK)Loading accessory from cache: Front Door
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalFound 6 devices in config
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalRestoring existing accessory from cache: Entry Hall Lights
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalRestoring existing accessory from cache: Family room lamps
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalRestoring existing accessory from cache: Nightstand lamps
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalRestoring existing accessory from cache: Living Room lamps
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalRestoring existing accessory from cache: Porch lights
12/3/2023, 9:32:48 AMHoobs bridgeInsteonLocalRestoring existing accessory from cache: Basement leak sensor
12/3/2023, 9:32:48 AMHoobs bridgeHomebridgeAlexaSmartHomeLogin required because existing authentication not found
12/3/2023, 9:32:48 AMHoobs bridgeHomebridgeAlexaSmartHomeAlexa-Remote: No cookie given, generate one
12/3/2023, 9:32:48 AMHoobs bridgeHomebridgeAlexaSmartHomeAlexa-Remote: Error from retrieving cookies
12/3/2023, 9:32:48 AMHoobs bridgeBridge is running on port 51826.
12/3/2023, 9:32:48 AMHoobs bridgeHomebridgeAlexaSmartHomeERRORFailed to initialize connection to Alexa. - Please open http://hoobs.local:2345/ with your browser and login to Amazon. The cookie will be output here after successfull login.
12/3/2023, 9:32:49 AMHoobs bridgeHomebridgeAlexaSmartHomeAlexa-Remote: Authentication check Error, try re-init
12/3/2023, 9:32:49 AMHoobs bridgeHomebridgeAlexaSmartHomeAlexa-Remote: No cookie given, generate one
12/3/2023, 9:32:49 AMHoobs bridgeHomebridgeAlexaSmartHomeAlexa-Remote: Error from retrieving cookies
12/3/2023, 9:32:49 AMHoobs bridgeHomebridgeAlexaSmartHomeAlexa-Remote: Authentication check Error and renew unsuccessful. STOP
12/3/2023, 9:32:49 AMHoobs bridgeHomebridgeAlexaSmartHomeERRORAfter initialization - HttpError(Error getting smart home devices. Reason: Cookie invalid, Renew unsuccessful)
12/3/2023, 9:32:49 AMHo

**Plugin Config:**

    "platform": "HomebridgeAlexaSmartHome",    "amazonDomain": "amazon.com",    "auth": {        "refreshInterval": 4,        "proxy": {            "clientHost": "hoobs.local",            "port": 2345        }    },    "language": "en-US",    "devices": [        "Living room thermostat"    ],    "debug": true}

**Screenshots:**

**Environment:**

- **Plugin Version**: 2.0.3
- **Homebridge Version**: 1.6.0
- **Node.js Version**: 16.20.2
- **NPM Version**:  hoobs 4.3.0
- **Operating System**: Raspbian

**Comment by joeyhage** [comment]
Hi @jayewyo, I am not a HOOBS user or developer so this plugin is not guaranteed to be compatible with HOOBS. I am not aware of any HOOBS users that have been successful. See https://github.com/joeyhage/homebridge-alexa-smarthome#compatibility
