### ISSUE TITLE
iOS Home widget doesn't accurately show On/Off status of devices pulled in from plugin

### ISSUE THREAD

**Issue by willryan042** [joeyhage/homebridge-alexa-smarthome#83]
**Describe Your Problem:**

I'm not sure if this is actually an issue caused by the plugin, but the iOS Home widget doesn't seem to update to accurately show the on/off status of devices pulled in by the plugin.

For example, if "Bedroom Lights" are on, the respective toggle in the widget sometimes shows them as off. If I tap it, the switch toggles on and nothing changes with the actual light. If I tap it again, the light will turn off as expected. Almost as if the devices in the widget need to update before they display their actual status.

And when I open the Home app, I notice my devices briefly display "Updating..." before correctly showing whether they're on or off, so I'm wondering if this is just the nature of how the plugin works.

**Logs:**

N/A

**Plugin Config:**

Haven't touched anything here but I'll paste it anyway:

```json
{
    "bridge": {
        "name": "Homebridge E66A",
        "username": "0E:F5:4C:4F:E6:6A",
        "port": 51199,
        "pin": "248-47-922",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "devices": [],
            "auth": {
                "refreshInterval": 4,
                "proxy": {
                    "clientHost": "192.168.0.169",
                    "port": 9001
                }
            },
            "amazonDomain": "amazon.com",
            "language": "en-US",
            "performance": {
                "cacheTTL": 30,
                "backgroundRefresh": false
            },
            "debug": false,
            "platform": "HomebridgeAlexaSmartHome"
        }
    ]
}
```

**Screenshots:**

N/A

**Environment:**

- **Plugin Version**: 2.0.4
- **Homebridge Version**: 1.7.0
- **Node.js Version**: v20.10.0
- **NPM Version**: not sure what this is, sorry!
- **Operating System**: macOS 14.2

**Comment by joeyhage** [comment]
Thanks for reaching out. This is by design. You can read more about the plugin performance settings if you are interested in adjusting how accessory states are refreshed.

**Comment by willryan042** [comment]
Awesome, thanks for the tip. So if I'm understanding some of the settings correctly, will enabling "Refresh device states automatically in the background" and keeping a low value for Device State Cache Lifetime essentially allow the iOS widget to be fairly "live" and update accurately?

**Comment by joeyhage** [comment]
Yep, that should help! It won’t refresh faster than every 60 seconds or so, unfortunately, otherwise you will get blocked by Amazon temporarily.
