### ISSUE TITLE
list of accessories to add

### ISSUE THREAD

**Issue by and43a** [joeyhage/homebridge-alexa-smarthome#85]
First I thank you for your beautiful work.
I just wanted to ask you why the list of accessories to add doesn't work for me. 

it is written that if nothing is specified, all accessories are added to homekit.

![Screenshot 2023-12-26 alle 19 42 04](https://github.com/joeyhage/homebridge-alexa-smarthome/assets/123098088/83f62cae-13e0-4f4a-9052-bb9693970cae)

I tried to insert accessories such as sockets or lights, but to no avail, all the accessories present in Alexa are displayed on Homekit.
maybe it would be nice to have a real list to flag the various accessories you want to have, thanks.

**Comment by joeyhage** [comment]
Hi @and43a, the list of device names needs to be the custom name you chose for the device such as “Front Door Light” or “Main Bedroom Lamp”. 

Since these could be anything, it’s not possible to have a list because Homebridge plugins can’t change what the settings page shows. In other words, I can’t customize each user’s settings page.

also, each time plugin settings change the child bridge (if you have it enabled) or the entire homebridge server needs to be restarted.

**Comment by and43a** [comment]
Thank you for the explanation. Merry ChristmasIl giorno 26 dic 2023, alle ore 23:27, Joey Hage ***@***.***> ha scritto:Hi @and43a, the list of device names needs to be the custom name you chose for the device such as “Front Door Light” or “Main Bedroom Lamp”.
Since these could be anything, it’s not possible to have a list because Homebridge plugins can’t change what the settings page shows. In other words, I can’t customize each user’s settings page.
also, each time plugin settings change the child bridge (if you have it enabled) or the entire homebridge server needs to be restarted.

**Comment by and43a** [comment]
everything workedIl giorno 27 dic 2023, alle ore 07:38, Andrea Russo ***@***.***> ha scritto:﻿Thank you for the explanation. Merry ChristmasIl giorno 26 dic 2023, alle ore 23:27, Joey Hage ***@***.***> ha scritto:Hi @and43a, the list of device names needs to be the custom name you chose for the device such as “Front Door Light” or “Main Bedroom Lamp”.
Since these could be anything, it’s not possible to have a list because Homebridge plugins can’t change what the settings page shows. In other words, I can’t customize each user’s settings page.
also, each time plugin settings change the child bridge (if you have it enabled) or the entire homebridge server needs to be restarted.
